const {
  red, green, blue, yellow,
  gold, silver, cristal,
  ruby, sapphire, fireRed, leafGreen, emerald,
  pearl, diamond, platinium, heartGold, soulSilver,
  black, white, black2, white2,
  omega_ruby, alpha_sapphire, x, y,
  sun, moon, ultra_sun, ultra_moon,
  sword, shield, brilliant_diamond, shining_pearl
} = require("../../_enums/gamesId.enum")

module.exports = class PagePokedex {
  static generationsSectionSelector = [
    'Generation_I_Pok',
    'Generation_II_Pok',
    'Generation_III_Pok',
    'Generation_IV_Pok',
    'Generation_V_Pok',
    'Generation_VI_Pok',
    'Generation_VII_Pok',
    'Generation_VIII_Pok',
  ]
  /** Order of columns on generation section */
  static gamesIndexByGeneration = [
    /** Gen. 1 */
    {
      [red]: 3,
      [green]: 4,
      [blue]: 5,
      [yellow]: 6,
      [gold]: 7,
      [silver]: 8,
      [cristal]: 9,
      [ruby]: 10,
      [sapphire]: 11,
      [fireRed]: 12,
      [leafGreen]: 13,
      [emerald]: 14,
      [diamond]: 17,
      [pearl]: 18,
      [platinium]: 19,
      [heartGold]: 20,
      [soulSilver]: 21,
      [black]: 23,
      [white]: 24,
      [black2]: 25,
      [white2]: 26,
      [x]: 27,
      [y]: 38,
      [alpha_sapphire]: 29,
      [omega_ruby]: 30,
      [sun]: 31,
      [moon]: 32,
      [ultra_sun]: 33,
      [ultra_moon]: 34,
      [sword]: 37,
      [shield]: 38,
      [brilliant_diamond]: 39,
      [shining_pearl]: 40
    },
    /** Gen. 2 */
    {
      [gold]: 3,
      [silver]: 4,
      [cristal]: 5,
      [ruby]: 6,
      [sapphire]: 7,
      [fireRed]: 8,
      [leafGreen]: 9,
      [emerald]: 10,
      [diamond]: 13,
      [pearl]: 14,
      [platinium]: 15,
      [heartGold]: 16,
      [soulSilver]: 17,
      [black]: 19,
      [white]: 20,
      [black2]: 21,
      [white2]: 22,
      [x]: 23,
      [y]: 24,
      [alpha_sapphire]: 25,
      [omega_ruby]: 26,
      [sun]: 27,
      [moon]: 28,
      [ultra_sun]: 29,
      [ultra_moon]: 30,
      [sword]: 31,
      [shield]: 32,
      [brilliant_diamond]: 33,
      [shining_pearl]: 34
    },
    /** Gen. 3 */
    {
      [ruby]: 3,
      [sapphire]: 4,
      [fireRed]: 5,
      [leafGreen]: 6,
      [emerald]: 7,
      [diamond]: 10,
      [pearl]: 11,
      [platinium]: 12,
      [heartGold]: 13,
      [soulSilver]: 14,
      [black]: 16,
      [white]: 17,
      [black2]: 18,
      [white2]: 19,
      [x]: 20,
      [y]: 21,
      [alpha_sapphire]: 22,
      [omega_ruby]: 23,
      [sun]: 24,
      [moon]: 25,
      [ultra_sun]: 26,
      [ultra_moon]: 27,
      [sword]: 28,
      [shield]: 29,
      [brilliant_diamond]: 30,
      [shining_pearl]: 31
    },
    /** Gen. 4 */
    {
      [diamond]: 3,
      [pearl]: 4,
      [platinium]: 5,
      [heartGold]: 6,
      [soulSilver]: 7,
      [black]: 9,
      [white]: 10,
      [black2]: 11,
      [white2]: 12,
      [x]: 13,
      [y]: 14,
      [alpha_sapphire]: 15,
      [omega_ruby]: 16,
      [sun]: 17,
      [moon]: 18,
      [ultra_sun]: 19,
      [ultra_moon]: 20,
      [sword]: 21,
      [shield]: 22,
      [brilliant_diamond]: 23,
      [shining_pearl]: 24
    },
    /** Gen. 5 */
    {
      [black]: 3,
      [white]: 4,
      [black2]: 5,
      [white2]: 6,
      [x]: 7,
      [y]: 8,
      [alpha_sapphire]: 9,
      [omega_ruby]: 10,
      [sun]: 11,
      [moon]: 12,
      [ultra_sun]: 13,
      [ultra_moon]: 14,
      [sword]: 15,
      [shield]: 16,
      [brilliant_diamond]: 17,
      [shining_pearl]: 18
    },
    /** Gen. 6 */
    {
      [x]: 3,
      [y]: 4,
      [alpha_sapphire]: 5,
      [omega_ruby]: 6,
      [sun]: 7,
      [moon]: 8,
      [ultra_sun]: 9,
      [ultra_moon]: 10,
      [sword]: 11,
      [shield]: 12,
      [brilliant_diamond]: 13,
      [shining_pearl]: 14
    },
    /** Gen. 7 */
    {
      [sun]: 3,
      [moon]: 4,
      [ultra_sun]: 5,
      [ultra_moon]: 6,
      [sword]: 7,
      [shield]: 8,
      [brilliant_diamond]: 9,
      [shining_pearl]: 10
    },
    /** Gen. 8 */
    {
      [sword]: 3,
      [shield]: 4,
      [brilliant_diamond]: 5,
      [shining_pearl]: 6
    }
  ]
}