import AvailabilitiesEnum from '../../../../_enums/availabilities.enum'
import GamesIdEnum from '../../../../_enums/gamesId.enum'

export const generationsSectionSelector = [
    'Generation_I_Pok',
    'Generation_II_Pok',
    'Generation_III_Pok',
    'Generation_IV_Pok',
    'Generation_V_Pok',
    'Generation_VI_Pok',
    'Generation_VII_Pok',
    'Generation_VIII_Pok',
  ]
  
/** Order of columns on generation section */
export const gamesIndexByGeneration = [
  /** Gen. 1 */
  {
    [GamesIdEnum.red]: 3,
    [GamesIdEnum.green]: 4,
    [GamesIdEnum.blue]: 5,
    [GamesIdEnum.yellow]: 6,
    [GamesIdEnum.gold]: 7,
    [GamesIdEnum.silver]: 8,
    [GamesIdEnum.crystal]: 9,
    [GamesIdEnum.ruby]: 10,
    [GamesIdEnum.sapphire]: 11,
    [GamesIdEnum.fireRed]: 12,
    [GamesIdEnum.leafGreen]: 13,
    [GamesIdEnum.emerald]: 14,
    [GamesIdEnum.diamond]: 17,
    [GamesIdEnum.pearl]: 18,
    [GamesIdEnum.platinium]: 19,
    [GamesIdEnum.heartGold]: 20,
    [GamesIdEnum.soulSilver]: 21,
    [GamesIdEnum.black]: 23,
    [GamesIdEnum.white]: 24,
    [GamesIdEnum.black2]: 25,
    [GamesIdEnum.white2]: 26,
    [GamesIdEnum.x]: 27,
    [GamesIdEnum.y]: 38,
    [GamesIdEnum.alpha_sapphire]: 29,
    [GamesIdEnum.omega_ruby]: 30,
    [GamesIdEnum.sun]: 31,
    [GamesIdEnum.moon]: 32,
    [GamesIdEnum.ultra_sun]: 33,
    [GamesIdEnum.ultra_moon]: 34,
    [GamesIdEnum.sword]: 37,
    [GamesIdEnum.shield]: 38,
    [GamesIdEnum.brilliant_diamond]: 39,
    [GamesIdEnum.shining_pearl]: 40
  },
  /** Gen. 2 */
  {
    [GamesIdEnum.gold]: 3,
    [GamesIdEnum.silver]: 4,
    [GamesIdEnum.crystal]: 5,
    [GamesIdEnum.ruby]: 6,
    [GamesIdEnum.sapphire]: 7,
    [GamesIdEnum.fireRed]: 8,
    [GamesIdEnum.leafGreen]: 9,
    [GamesIdEnum.emerald]: 10,
    [GamesIdEnum.diamond]: 13,
    [GamesIdEnum.pearl]: 14,
    [GamesIdEnum.platinium]: 15,
    [GamesIdEnum.heartGold]: 16,
    [GamesIdEnum.soulSilver]: 17,
    [GamesIdEnum.black]: 19,
    [GamesIdEnum.white]: 20,
    [GamesIdEnum.black2]: 21,
    [GamesIdEnum.white2]: 22,
    [GamesIdEnum.x]: 23,
    [GamesIdEnum.y]: 24,
    [GamesIdEnum.alpha_sapphire]: 25,
    [GamesIdEnum.omega_ruby]: 26,
    [GamesIdEnum.sun]: 27,
    [GamesIdEnum.moon]: 28,
    [GamesIdEnum.ultra_sun]: 29,
    [GamesIdEnum.ultra_moon]: 30,
    [GamesIdEnum.sword]: 31,
    [GamesIdEnum.shield]: 32,
    [GamesIdEnum.brilliant_diamond]: 33,
    [GamesIdEnum.shining_pearl]: 34
  },
  /** Gen. 3 */
  {
    [GamesIdEnum.ruby]: 3,
    [GamesIdEnum.sapphire]: 4,
    [GamesIdEnum.fireRed]: 5,
    [GamesIdEnum.leafGreen]: 6,
    [GamesIdEnum.emerald]: 7,
    [GamesIdEnum.diamond]: 10,
    [GamesIdEnum.pearl]: 11,
    [GamesIdEnum.platinium]: 12,
    [GamesIdEnum.heartGold]: 13,
    [GamesIdEnum.soulSilver]: 14,
    [GamesIdEnum.black]: 16,
    [GamesIdEnum.white]: 17,
    [GamesIdEnum.black2]: 18,
    [GamesIdEnum.white2]: 19,
    [GamesIdEnum.x]: 20,
    [GamesIdEnum.y]: 21,
    [GamesIdEnum.alpha_sapphire]: 22,
    [GamesIdEnum.omega_ruby]: 23,
    [GamesIdEnum.sun]: 24,
    [GamesIdEnum.moon]: 25,
    [GamesIdEnum.ultra_sun]: 26,
    [GamesIdEnum.ultra_moon]: 27,
    [GamesIdEnum.sword]: 28,
    [GamesIdEnum.shield]: 29,
    [GamesIdEnum.brilliant_diamond]: 30,
    [GamesIdEnum.shining_pearl]: 31
  },
  /** Gen. 4 */
  {
    [GamesIdEnum.diamond]: 3,
    [GamesIdEnum.pearl]: 4,
    [GamesIdEnum.platinium]: 5,
    [GamesIdEnum.heartGold]: 6,
    [GamesIdEnum.soulSilver]: 7,
    [GamesIdEnum.black]: 9,
    [GamesIdEnum.white]: 10,
    [GamesIdEnum.black2]: 11,
    [GamesIdEnum.white2]: 12,
    [GamesIdEnum.x]: 13,
    [GamesIdEnum.y]: 14,
    [GamesIdEnum.alpha_sapphire]: 15,
    [GamesIdEnum.omega_ruby]: 16,
    [GamesIdEnum.sun]: 17,
    [GamesIdEnum.moon]: 18,
    [GamesIdEnum.ultra_sun]: 19,
    [GamesIdEnum.ultra_moon]: 20,
    [GamesIdEnum.sword]: 21,
    [GamesIdEnum.shield]: 22,
    [GamesIdEnum.brilliant_diamond]: 23,
    [GamesIdEnum.shining_pearl]: 24
  },
  /** Gen. 5 */
  {
    [GamesIdEnum.black]: 3,
    [GamesIdEnum.white]: 4,
    [GamesIdEnum.black2]: 5,
    [GamesIdEnum.white2]: 6,
    [GamesIdEnum.x]: 7,
    [GamesIdEnum.y]: 8,
    [GamesIdEnum.alpha_sapphire]: 9,
    [GamesIdEnum.omega_ruby]: 10,
    [GamesIdEnum.sun]: 11,
    [GamesIdEnum.moon]: 12,
    [GamesIdEnum.ultra_sun]: 13,
    [GamesIdEnum.ultra_moon]: 14,
    [GamesIdEnum.sword]: 15,
    [GamesIdEnum.shield]: 16,
    [GamesIdEnum.brilliant_diamond]: 17,
    [GamesIdEnum.shining_pearl]: 18
  },
  /** Gen. 6 */
  {
    [GamesIdEnum.x]: 3,
    [GamesIdEnum.y]: 4,
    [GamesIdEnum.alpha_sapphire]: 5,
    [GamesIdEnum.omega_ruby]: 6,
    [GamesIdEnum.sun]: 7,
    [GamesIdEnum.moon]: 8,
    [GamesIdEnum.ultra_sun]: 9,
    [GamesIdEnum.ultra_moon]: 10,
    [GamesIdEnum.sword]: 11,
    [GamesIdEnum.shield]: 12,
    [GamesIdEnum.brilliant_diamond]: 13,
    [GamesIdEnum.shining_pearl]: 14
  },
  /** Gen. 7 */
  {
    [GamesIdEnum.sun]: 3,
    [GamesIdEnum.moon]: 4,
    [GamesIdEnum.ultra_sun]: 5,
    [GamesIdEnum.ultra_moon]: 6,
    [GamesIdEnum.sword]: 7,
    [GamesIdEnum.shield]: 8,
    [GamesIdEnum.brilliant_diamond]: 9,
    [GamesIdEnum.shining_pearl]: 10
  },
  /** Gen. 8 */
  {
    [GamesIdEnum.sword]: 3,
    [GamesIdEnum.shield]: 4,
    [GamesIdEnum.brilliant_diamond]: 5,
    [GamesIdEnum.shining_pearl]: 6
  }
]

export const availabilityChars = {
  'C': AvailabilitiesEnum.caught,
  'S': AvailabilitiesEnum.swarm,
  'D': AvailabilitiesEnum.dual,
  'R': AvailabilitiesEnum.received,
  'E': AvailabilitiesEnum.evolved,
  'B': AvailabilitiesEnum.bred,
  'CD': AvailabilitiesEnum.paid_dlc,
  'DA': AvailabilitiesEnum.dynamax,
  'CC': AvailabilitiesEnum.core,
  'FS': AvailabilitiesEnum.firend_safari,
  'EV': AvailabilitiesEnum.distribution,
  'DR': AvailabilitiesEnum.dream_radar,
  'DW': AvailabilitiesEnum.dream_world,
  'ET': AvailabilitiesEnum.trade_evolved,
  'Ev': AvailabilitiesEnum.event,
  'T': AvailabilitiesEnum.trade
}